CREATE TABLE TB_MULTA
(
   ID_MULTA               INTEGER           NOT NULL,
   ID_USUARIO             INTEGER,
   ID_DEVOLUCAO           INTEGER,
   VALOR_MULTA            DECIMAL(10,2),
   DTH_APLICACAO          TIMESTAMP,
   constraint PK_TB_MULTA primary key (ID_MULTA),
   CONSTRAINT FK_TB_MULTA_TB_DEVOLUCAO FOREIGN KEY (ID_DEVOLUCAO) REFERENCES TB_DEVOLUCAO (ID_DEVOLUCAO) ON DELETE RESTRICT ON UPDATE CASCADE,
   CONSTRAINT FK_TB_MULTA_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE RESTRICT ON UPDATE CASCADE
);
