CREATE TABLE TB_FUNCIONARIO
(
   ID_FUNCIONARIO       INTEGER              NOT NULL,
   ID_USUARIO           INTEGER,
   DSC_CARGO            VARCHAR(50)          NOT NULL,
   VLR_SALARIO          DECIMAL(10,2)        NOT NULL,
   NUM_CTPS             VARCHAR(11)          NOT NULL,
   DAT_ADMISSAO         DATE                 DEFAULT CURRENT_DATE NOT NULL,
   CONSTRAINT PK_TB_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO)
);
