CREATE TABLE TB_MULTA
(
   ID_MULTA               INTEGER NOT NULL PRIMARY KEY IDENTITY,
   ID_USUARIO             INTEGER,
   ID_DEVOLUCAO           INTEGER,
   VALOR_MULTA            DECIMAL(10,2),
   DTH_APLICACAO          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT FK_TB_MULTA_TB_DEVOLUCAO FOREIGN KEY (ID_DEVOLUCAO) REFERENCES TB_DEVOLUCAO (ID_DEVOLUCAO) ON DELETE RESTRICT ON UPDATE CASCADE,
   CONSTRAINT FK_TB_MULTA_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE RESTRICT ON UPDATE CASCADE
);
