CREATE TABLE TB_LOCATARIO
(
   ID_LOCATARIO         INTEGER              NOT NULL,
   ID_USUARIO           INTEGER,
   ENDERECO_LOCATARIO   VARCHAR(255)         NOT NULL,
   CPF_LOCATARIO        VARCHAR(11)          NOT NULL,
   TELEFONE_LOCATARIO   VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_TB_LOCATARIO PRIMARY KEY (ID_LOCATARIO)
);
