CREATE TABLE TB_LOCATARIO
(
   ID_LOCATARIO         INTEGER NOT NULL PRIMARY KEY IDENTITY,
   ID_USUARIO           INTEGER,
   ENDERECO_LOCATARIO   VARCHAR(255)                        not null,
   CPF_LOCATARIO        VARCHAR(11)                         not null,
   TELEFONE_LOCATARIO   VARCHAR(20)                         not null,
   CONSTRAINT FK_TB_LOCATARIO_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE RESTRICT ON UPDATE CASCADE
);