ALTER TABLE TB_ITEM
ADD CONSTRAINT UQ_TB_ITEM_ID_AUTOR_TITULO UNIQUE (ID_AUTOR, TITULO);

ALTER TABLE TB_LOCATARIO
ADD CONSTRAINT UQ_TB_LOCATARIO_CPF UNIQUE (CPF_LOCATARIO);

ALTER TABLE TB_USUARIO
ADD CONSTRAINT UQ_TB_USUARIO_EMAIL UNIQUE (EMAIL);

ALTER TABLE TB_EDITORA
ADD CONSTRAINT UQ_TB_EDITORA_NOME_EDITORA UNIQUE (NOME_EDITORA);
