create table TB_EDITORA
(
   ID_EDITORA           INTEGER NOT NULL PRIMARY KEY IDENTITY,
   NOME_EDITORA         VARCHAR(100)                         NOT NULL,
   ENDERECO_EDITORA     VARCHAR(255)                         NOT NULL,
   TELEFONE_EDITORA     VARCHAR(255)                         NOT NULL,
   DTH_CADASTRO_EDITORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL
);