CREATE TABLE TB_AUTOR
(
   ID_AUTOR             INTEGER              NOT NULL,
   NOME_AUTOR           VARCHAR(255)         NOT NULL,
   DAT_NASCIMENTO       DATE                 NOT NULL,
   BIOGRAFIA            VARCHAR(255),
   DTH_CADASTRO_AUTOR   TIMESTAMP            NOT NULL,
   CONSTRAINT PK_TB_AUTOR PRIMARY KEY (ID_AUTOR)
);
