CREATE TABLE TB_GENERO
(
   ID_GENERO            INTEGER              NOT NULL,
   NOME_GENERO          VARCHAR(20)          NOT NULL,
   DTH_CADASTRO_GENERO  TIMESTAMP            NOT NULL,
   CONSTRAINT PK_TB_GENERO PRIMARY KEY (ID_GENERO)
);
