CREATE TABLE TB_LIVRO
(
   ID_LIVRO             VARCHAR(255)              NOT NULL,
   ID_ITEM              VARCHAR(255),
   NUM_ISBN             VARCHAR(20)          NOT NULL,
   SINOPSE              VARCHAR(4000),
   IDIOMA               VARCHAR(50)          NOT NULL,
   CONSTRAINT PK_TB_LIVRO PRIMARY KEY (ID_LIVRO),
   CONSTRAINT FK_LIVRO_ID_ITEM FOREIGN KEY (ID_ITEM) REFERENCES TB_ITEM (ID_ITEM) ON DELETE CASCADE ON UPDATE CASCADE
);
