CREATE TABLE TB_REVISTA
(
   ID_REVISTA           INTEGER NOT NULL PRIMARY KEY IDENTITY,
   ID_ITEM              INTEGER NOT NULL,
   ISSN                 VARCHAR(20) NOT NULL,
   FREQUENCIA_PUBLICACAO VARCHAR(50),
   CONSTRAINT FK_TB_REVISTA_TB_ITEM FOREIGN KEY (ID_ITEM) REFERENCES TB_ITEM (ID_ITEM)
);