CREATE TABLE TB_USUARIO
(
   ID_USUARIO           INTEGER              NOT NULL,
   NOME_USUARIO         VARCHAR(100)         NOT NULL,
   EMAIL                VARCHAR(40)          NOT NULL,
   SENHA_USUARIO        VARCHAR(255)         NOT NULL,
   DTH_CADASTRO_USUARIO TIMESTAMP            NOT NULL,
   CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO)
);
