CREATE TABLE TB_EMPRESTIMO
(
   ID_EMPRESTIMO        INTEGER              NOT NULL,
   ID_USUARIO           INTEGER              NOT NULL,
   ID_ITEM              INTEGER,
   DTH_EMPRESTIMO       TIMESTAMP            NOT NULL,
   DTH_DEVOLUCAO_PREVISTA DATE               NOT NULL,
   DAT_DEVOLUCAO_REAL   DATE,
   VALOR_MULTA          DECIMAL(10,2),
   DTH_MULTA            TIMESTAMP,
   CONSTRAINT PK_TB_EMPRESTIMO PRIMARY KEY (ID_EMPRESTIMO)
);
