CREATE TABLE TB_DEVOLUCAO
(
   ID_DEVOLUCAO          INTEGER NOT NULL PRIMARY KEY IDENTITY,
   ID_EMPRESTIMO         INTEGER,
   DAT_DEVOLUCAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL,
   CONSTRAINT FK_TB_DEVOLUCAO_TB_EMPRESTIMO FOREIGN KEY (ID_EMPRESTIMO) REFERENCES TB_EMPRESTIMO (ID_EMPRESTIMO) ON DELETE RESTRICT ON UPDATE CASCADE
);
