CREATE TABLE TB_DEVOLUCAO
(
   ID_DEVOLUCAO          INTEGER              NOT NULL,
   ID_EMPRESTIMO         INTEGER,
   DAT_DEVOLUCAO         TIMESTAMP            NOT NULL,
   CONSTRAINT PK_TB_DEVOLUCAO PRIMARY KEY (ID_DEVOLUCAO),
   CONSTRAINT FK_TB_DEVOLUCAO_TB_EMPRESTIMO FOREIGN KEY (ID_EMPRESTIMO) REFERENCES TB_EMPRESTIMO (ID_EMPRESTIMO) ON DELETE RESTRICT ON UPDATE CASCADE
);
