CREATE TABLE TB_RESERVA
(
   ID_RESERVA           INTEGER NOT NULL PRIMARY KEY IDENTITY,
   ID_USUARIO           INTEGER,
   ID_ITEM             INTEGER,
   IND_ATENDIDA         VARCHAR(1)                                     NOT NULL,
   DTH_RESERVA          TIMESTAMP DEFAULT CURRENT_TIMESTAMP            NOT NULL,
   CONSTRAINT FK_TB_RESERVA_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE RESTRICT ON UPDATE CASCADE,
   CONSTRAINT FK_TB_RESERVA_TB_ITEM FOREIGN KEY (ID_ITEM) REFERENCES TB_ITEM (ID_ITEM) ON DELETE RESTRICT ON UPDATE CASCADE
);
