CREATE TABLE TB_RESERVA
(
   ID_RESERVA           INTEGER              NOT NULL,
   ID_USUARIO           INTEGER,
   ID_ITEM              INTEGER,
   IND_ATENDIDA         VARCHAR(1)           NOT NULL,
   DTH_RESERVA          TIMESTAMP            NOT NULL,
   CONSTRAINT PK_TB_RESERVA PRIMARY KEY (ID_RESERVA)
);
